# Generated by Django 4.2.3 on 2023-07-08 12:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continuous_assessment', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('exam', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
            ],
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('assessment_scores', models.ManyToManyField(to='career.assessmentscore')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='grade_level',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='career.gradelevel'),
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='session_term',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='career.sessionterm'),
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='career.subject'),
        ),
    ]
