# Generated by Django 4.2.3 on 2023-07-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentscore',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.gradelevel'),
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='session_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.sessionterm'),
        ),
    ]
