# Generated by Django 4.2.3 on 2023-07-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_assessmentscore_grade_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentscore',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.subject'),
        ),
    ]
