# Generated by Django 4.2.3 on 2023-07-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_alter_assessmentscore_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentscore',
            unique_together={('subject', 'session_term')},
        ),
    ]
