# Generated by Django 4.2.3 on 2023-07-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_remove_student_assessment_scores_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentscore',
            unique_together={('student', 'subject', 'session_term', 'grade_level')},
        ),
    ]
