# Generated by Django 4.2.3 on 2023-07-12 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_alter_assessmentscore_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='career.subjectfield'),
        ),
    ]
