# Generated by Django 4.2.3 on 2023-07-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0009_student_entry_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entry_code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
