# Generated by Django 4.2.3 on 2023-07-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0010_alter_student_entry_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentscore',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
