# Generated by Django 5.0.4 on 2024-04-15 16:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0013_student_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentscore',
            options={'ordering': ['grade_level', 'session_term'], 'verbose_name': 'Assessment Score', 'verbose_name_plural': 'Assessment Scores'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['name'], 'verbose_name': 'Discipline', 'verbose_name_plural': 'Disciplines'},
        ),
        migrations.AlterModelOptions(
            name='gradelevel',
            options={'ordering': ['name'], 'verbose_name': 'Grade Level', 'verbose_name_plural': 'Grade Levels'},
        ),
        migrations.AlterModelOptions(
            name='sessionterm',
            options={'ordering': ['name'], 'verbose_name': 'Session Term', 'verbose_name_plural': 'Session Terms'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_field'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='subjectfield',
            options={'ordering': ['name'], 'verbose_name': 'Subject Field', 'verbose_name_plural': 'Subject Fields'},
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discipline',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sessionterm',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionterm',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subjectfield',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectfield',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='continuous_assessment',
            field=models.PositiveIntegerField(help_text='Enter the continuous assessment score (0-40).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='continuous assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='exam',
            field=models.PositiveIntegerField(help_text='Enter the exam score (0-60).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='exam'),
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='grade_level',
            field=models.ForeignKey(help_text='Select the grade level for the assessment score.', on_delete=django.db.models.deletion.CASCADE, to='career.gradelevel', verbose_name='grade level'),
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='session_term',
            field=models.ForeignKey(help_text='Select the session term for the assessment score.', on_delete=django.db.models.deletion.CASCADE, to='career.sessionterm', verbose_name='session term'),
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='student',
            field=models.ForeignKey(help_text='Select the student associated with the assessment score.', null=True, on_delete=django.db.models.deletion.CASCADE, to='career.student', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='subject',
            field=models.ForeignKey(help_text='Select the subject for the assessment score.', on_delete=django.db.models.deletion.CASCADE, to='career.subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='total_score',
            field=models.PositiveIntegerField(default=0, help_text='Total score calculated as sum of continuous assessment and exam scores.', verbose_name='total score'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=models.TextField(help_text='Enter a description for the discipline.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(help_text='Enter the name of the discipline.', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='subject_field',
            field=models.ForeignKey(help_text='Select the subject field associated with this discipline.', on_delete=django.db.models.deletion.PROTECT, to='career.subjectfield', verbose_name='subject field'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='name',
            field=models.CharField(help_text='Enter the name of the grade level.', max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sessionterm',
            name='name',
            field=models.CharField(help_text='Enter the name of the session term.', max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(help_text='Enter the email address of the student.', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_code',
            field=models.CharField(help_text='Enter the unique entry code for the student.', max_length=7, unique=True, verbose_name='entry code'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Enter the name of the student.', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Enter the name of the subject.', max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_field',
            field=models.ForeignKey(blank=True, help_text='Select the subject field associated with this subject.', null=True, on_delete=django.db.models.deletion.PROTECT, to='career.subjectfield', verbose_name='subject field'),
        ),
        migrations.AlterField(
            model_name='subjectfield',
            name='name',
            field=models.CharField(help_text='Enter the name of the subject field.', max_length=50, unique=True, verbose_name='name'),
        ),
    ]
